### ISSUE TITLE
Removing auto-updating for Alfred Gallery

### ISSUE THREAD

**Issue by vitorgalvao** [kostyafarber/alfred-notable-workflow#2]
When [the Alfred Gallery](https://www.alfredforum.com/topic/19058-submitting-workflows-for-the-alfred-gallery/) is live, added workflows will be updatable from within Alfred itself. As part of that, a prerequisite for inclusion will be that workflows *not* auto-update themselves. This is to avoid a confusing interaction of crossed updates *and* for security reasons, as Gallery workflows go through a number of checks.

Your development process won’t change. You’ll still make GitHub releases as usual to update the workflow. We’ll detect when new releases are out and queue them up for a new review and update in the Gallery.

Disabling the auto-updating and making a new release helps to speed up the process, but if you prefer to wait I’ll ping you again once the Gallery is live.

**Comment by kostyafarber** [comment]
@vitorgalvao thanks for raising this. Let me know when the gallery is live and I will change.

**Comment by vitorgalvao** [comment]
[The Gallery is now in Early Access](https://www.alfredapp.com/blog/releases/alfred-gallery-now-in-early-access/), you can make the change.

**Comment by vitorgalvao** [comment]
@kostyafarber [The Gallery is now in Early Access](https://www.alfredapp.com/blog/releases/alfred-gallery-now-in-early-access/), you can make the change.

**Comment by kostyafarber** [comment]
Will implement in the next couple of days

**Comment by kostyafarber** [comment]
@vitorgalvao Done as of https://github.com/kostyafarber/alfred-notable-workflow/releases/tag/v1.0.1

**Comment by vitorgalvao** [comment]
Thank you. It will be live soon.
